services:
  profiles-svc:
    build: .
    container_name: profiles-svc
    ports:
      - "8002:8000"
    networks:
      - netbill-net

  profiles-svc-postgres:
    image: postgres:15
    container_name: profiles-svc-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "7002:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - netbill-net

  profiles-svc-swagger:
    image: swaggerapi/swagger-ui
    container_name: profiles-svc-swagger
    environment:
      - SWAGGER_JSON=/docs/api-bundled.yaml
    volumes:
      - ./docs:/docs:ro
    ports:
      - "5002:8080"
    networks:
      - netbill-net


volumes:
  pgdata:
  bundle:

networks:
  netbill-net:
    external: true
