/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UploadProfileMediaLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadProfileMediaLinks{}

// UploadProfileMediaLinks struct for UploadProfileMediaLinks
type UploadProfileMediaLinks struct {
	Data UploadProfileMediaLinksData `json:"data"`
	Included []ProfileData `json:"included"`
}

type _UploadProfileMediaLinks UploadProfileMediaLinks

// NewUploadProfileMediaLinks instantiates a new UploadProfileMediaLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadProfileMediaLinks(data UploadProfileMediaLinksData, included []ProfileData) *UploadProfileMediaLinks {
	this := UploadProfileMediaLinks{}
	this.Data = data
	this.Included = included
	return &this
}

// NewUploadProfileMediaLinksWithDefaults instantiates a new UploadProfileMediaLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadProfileMediaLinksWithDefaults() *UploadProfileMediaLinks {
	this := UploadProfileMediaLinks{}
	return &this
}

// GetData returns the Data field value
func (o *UploadProfileMediaLinks) GetData() UploadProfileMediaLinksData {
	if o == nil {
		var ret UploadProfileMediaLinksData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UploadProfileMediaLinks) GetDataOk() (*UploadProfileMediaLinksData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UploadProfileMediaLinks) SetData(v UploadProfileMediaLinksData) {
	o.Data = v
}

// GetIncluded returns the Included field value
func (o *UploadProfileMediaLinks) GetIncluded() []ProfileData {
	if o == nil {
		var ret []ProfileData
		return ret
	}

	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value
// and a boolean to check if the value has been set.
func (o *UploadProfileMediaLinks) GetIncludedOk() ([]ProfileData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Included, true
}

// SetIncluded sets field value
func (o *UploadProfileMediaLinks) SetIncluded(v []ProfileData) {
	o.Included = v
}

func (o UploadProfileMediaLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadProfileMediaLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["included"] = o.Included
	return toSerialize, nil
}

func (o *UploadProfileMediaLinks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"included",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadProfileMediaLinks := _UploadProfileMediaLinks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadProfileMediaLinks)

	if err != nil {
		return err
	}

	*o = UploadProfileMediaLinks(varUploadProfileMediaLinks)

	return err
}

type NullableUploadProfileMediaLinks struct {
	value *UploadProfileMediaLinks
	isSet bool
}

func (v NullableUploadProfileMediaLinks) Get() *UploadProfileMediaLinks {
	return v.value
}

func (v *NullableUploadProfileMediaLinks) Set(val *UploadProfileMediaLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadProfileMediaLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadProfileMediaLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadProfileMediaLinks(val *UploadProfileMediaLinks) *NullableUploadProfileMediaLinks {
	return &NullableUploadProfileMediaLinks{value: val, isSet: true}
}

func (v NullableUploadProfileMediaLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadProfileMediaLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


