/*
netbill profile-svc API

API documentation for profile-svc

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the DeleteUploadProfileAvatarDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadProfileAvatarDataAttributes{}

// DeleteUploadProfileAvatarDataAttributes struct for DeleteUploadProfileAvatarDataAttributes
type DeleteUploadProfileAvatarDataAttributes struct {
	// avatar media key
	AvatarKey *string `json:"avatar_key,omitempty"`
}

// NewDeleteUploadProfileAvatarDataAttributes instantiates a new DeleteUploadProfileAvatarDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadProfileAvatarDataAttributes() *DeleteUploadProfileAvatarDataAttributes {
	this := DeleteUploadProfileAvatarDataAttributes{}
	return &this
}

// NewDeleteUploadProfileAvatarDataAttributesWithDefaults instantiates a new DeleteUploadProfileAvatarDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadProfileAvatarDataAttributesWithDefaults() *DeleteUploadProfileAvatarDataAttributes {
	this := DeleteUploadProfileAvatarDataAttributes{}
	return &this
}

// GetAvatarKey returns the AvatarKey field value if set, zero value otherwise.
func (o *DeleteUploadProfileAvatarDataAttributes) GetAvatarKey() string {
	if o == nil || IsNil(o.AvatarKey) {
		var ret string
		return ret
	}
	return *o.AvatarKey
}

// GetAvatarKeyOk returns a tuple with the AvatarKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteUploadProfileAvatarDataAttributes) GetAvatarKeyOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarKey) {
		return nil, false
	}
	return o.AvatarKey, true
}

// HasAvatarKey returns a boolean if a field has been set.
func (o *DeleteUploadProfileAvatarDataAttributes) HasAvatarKey() bool {
	if o != nil && !IsNil(o.AvatarKey) {
		return true
	}

	return false
}

// SetAvatarKey gets a reference to the given string and assigns it to the AvatarKey field.
func (o *DeleteUploadProfileAvatarDataAttributes) SetAvatarKey(v string) {
	o.AvatarKey = &v
}

func (o DeleteUploadProfileAvatarDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadProfileAvatarDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvatarKey) {
		toSerialize["avatar_key"] = o.AvatarKey
	}
	return toSerialize, nil
}

type NullableDeleteUploadProfileAvatarDataAttributes struct {
	value *DeleteUploadProfileAvatarDataAttributes
	isSet bool
}

func (v NullableDeleteUploadProfileAvatarDataAttributes) Get() *DeleteUploadProfileAvatarDataAttributes {
	return v.value
}

func (v *NullableDeleteUploadProfileAvatarDataAttributes) Set(val *DeleteUploadProfileAvatarDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadProfileAvatarDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadProfileAvatarDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadProfileAvatarDataAttributes(val *DeleteUploadProfileAvatarDataAttributes) *NullableDeleteUploadProfileAvatarDataAttributes {
	return &NullableDeleteUploadProfileAvatarDataAttributes{value: val, isSet: true}
}

func (v NullableDeleteUploadProfileAvatarDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadProfileAvatarDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


