/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteUploadProfileAvatarDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadProfileAvatarDataAttributes{}

// DeleteUploadProfileAvatarDataAttributes struct for DeleteUploadProfileAvatarDataAttributes
type DeleteUploadProfileAvatarDataAttributes struct {
	// avatar media key
	AvatarKey string `json:"avatar_key"`
}

type _DeleteUploadProfileAvatarDataAttributes DeleteUploadProfileAvatarDataAttributes

// NewDeleteUploadProfileAvatarDataAttributes instantiates a new DeleteUploadProfileAvatarDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadProfileAvatarDataAttributes(avatarKey string) *DeleteUploadProfileAvatarDataAttributes {
	this := DeleteUploadProfileAvatarDataAttributes{}
	this.AvatarKey = avatarKey
	return &this
}

// NewDeleteUploadProfileAvatarDataAttributesWithDefaults instantiates a new DeleteUploadProfileAvatarDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadProfileAvatarDataAttributesWithDefaults() *DeleteUploadProfileAvatarDataAttributes {
	this := DeleteUploadProfileAvatarDataAttributes{}
	return &this
}

// GetAvatarKey returns the AvatarKey field value
func (o *DeleteUploadProfileAvatarDataAttributes) GetAvatarKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AvatarKey
}

// GetAvatarKeyOk returns a tuple with the AvatarKey field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadProfileAvatarDataAttributes) GetAvatarKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvatarKey, true
}

// SetAvatarKey sets field value
func (o *DeleteUploadProfileAvatarDataAttributes) SetAvatarKey(v string) {
	o.AvatarKey = v
}

func (o DeleteUploadProfileAvatarDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadProfileAvatarDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["avatar_key"] = o.AvatarKey
	return toSerialize, nil
}

func (o *DeleteUploadProfileAvatarDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"avatar_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteUploadProfileAvatarDataAttributes := _DeleteUploadProfileAvatarDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteUploadProfileAvatarDataAttributes)

	if err != nil {
		return err
	}

	*o = DeleteUploadProfileAvatarDataAttributes(varDeleteUploadProfileAvatarDataAttributes)

	return err
}

type NullableDeleteUploadProfileAvatarDataAttributes struct {
	value *DeleteUploadProfileAvatarDataAttributes
	isSet bool
}

func (v NullableDeleteUploadProfileAvatarDataAttributes) Get() *DeleteUploadProfileAvatarDataAttributes {
	return v.value
}

func (v *NullableDeleteUploadProfileAvatarDataAttributes) Set(val *DeleteUploadProfileAvatarDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadProfileAvatarDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadProfileAvatarDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadProfileAvatarDataAttributes(val *DeleteUploadProfileAvatarDataAttributes) *NullableDeleteUploadProfileAvatarDataAttributes {
	return &NullableDeleteUploadProfileAvatarDataAttributes{value: val, isSet: true}
}

func (v NullableDeleteUploadProfileAvatarDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadProfileAvatarDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


