/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProfile{}

// UpdateProfile struct for UpdateProfile
type UpdateProfile struct {
	Data UpdateProfileData `json:"data"`
}

type _UpdateProfile UpdateProfile

// NewUpdateProfile instantiates a new UpdateProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProfile(data UpdateProfileData) *UpdateProfile {
	this := UpdateProfile{}
	this.Data = data
	return &this
}

// NewUpdateProfileWithDefaults instantiates a new UpdateProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProfileWithDefaults() *UpdateProfile {
	this := UpdateProfile{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateProfile) GetData() UpdateProfileData {
	if o == nil {
		var ret UpdateProfileData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateProfile) GetDataOk() (*UpdateProfileData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateProfile) SetData(v UpdateProfileData) {
	o.Data = v
}

func (o UpdateProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateProfile := _UpdateProfile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateProfile)

	if err != nil {
		return err
	}

	*o = UpdateProfile(varUpdateProfile)

	return err
}

type NullableUpdateProfile struct {
	value *UpdateProfile
	isSet bool
}

func (v NullableUpdateProfile) Get() *UpdateProfile {
	return v.value
}

func (v *NullableUpdateProfile) Set(val *UpdateProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProfile(val *UpdateProfile) *NullableUpdateProfile {
	return &NullableUpdateProfile{value: val, isSet: true}
}

func (v NullableUpdateProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


