/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteUploadProfileAvatar type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadProfileAvatar{}

// DeleteUploadProfileAvatar struct for DeleteUploadProfileAvatar
type DeleteUploadProfileAvatar struct {
	Data DeleteUploadProfileAvatarData `json:"data"`
}

type _DeleteUploadProfileAvatar DeleteUploadProfileAvatar

// NewDeleteUploadProfileAvatar instantiates a new DeleteUploadProfileAvatar object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadProfileAvatar(data DeleteUploadProfileAvatarData) *DeleteUploadProfileAvatar {
	this := DeleteUploadProfileAvatar{}
	this.Data = data
	return &this
}

// NewDeleteUploadProfileAvatarWithDefaults instantiates a new DeleteUploadProfileAvatar object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadProfileAvatarWithDefaults() *DeleteUploadProfileAvatar {
	this := DeleteUploadProfileAvatar{}
	return &this
}

// GetData returns the Data field value
func (o *DeleteUploadProfileAvatar) GetData() DeleteUploadProfileAvatarData {
	if o == nil {
		var ret DeleteUploadProfileAvatarData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadProfileAvatar) GetDataOk() (*DeleteUploadProfileAvatarData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeleteUploadProfileAvatar) SetData(v DeleteUploadProfileAvatarData) {
	o.Data = v
}

func (o DeleteUploadProfileAvatar) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadProfileAvatar) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeleteUploadProfileAvatar) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteUploadProfileAvatar := _DeleteUploadProfileAvatar{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteUploadProfileAvatar)

	if err != nil {
		return err
	}

	*o = DeleteUploadProfileAvatar(varDeleteUploadProfileAvatar)

	return err
}

type NullableDeleteUploadProfileAvatar struct {
	value *DeleteUploadProfileAvatar
	isSet bool
}

func (v NullableDeleteUploadProfileAvatar) Get() *DeleteUploadProfileAvatar {
	return v.value
}

func (v *NullableDeleteUploadProfileAvatar) Set(val *DeleteUploadProfileAvatar) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadProfileAvatar) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadProfileAvatar) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadProfileAvatar(val *DeleteUploadProfileAvatar) *NullableDeleteUploadProfileAvatar {
	return &NullableDeleteUploadProfileAvatar{value: val, isSet: true}
}

func (v NullableDeleteUploadProfileAvatar) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadProfileAvatar) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


