/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the DeleteUploadProfileAvatarData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadProfileAvatarData{}

// DeleteUploadProfileAvatarData struct for DeleteUploadProfileAvatarData
type DeleteUploadProfileAvatarData struct {
	// account id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes DeleteUploadProfileAvatarDataAttributes `json:"attributes"`
}

type _DeleteUploadProfileAvatarData DeleteUploadProfileAvatarData

// NewDeleteUploadProfileAvatarData instantiates a new DeleteUploadProfileAvatarData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadProfileAvatarData(id uuid.UUID, type_ string, attributes DeleteUploadProfileAvatarDataAttributes) *DeleteUploadProfileAvatarData {
	this := DeleteUploadProfileAvatarData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewDeleteUploadProfileAvatarDataWithDefaults instantiates a new DeleteUploadProfileAvatarData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadProfileAvatarDataWithDefaults() *DeleteUploadProfileAvatarData {
	this := DeleteUploadProfileAvatarData{}
	return &this
}

// GetId returns the Id field value
func (o *DeleteUploadProfileAvatarData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadProfileAvatarData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeleteUploadProfileAvatarData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *DeleteUploadProfileAvatarData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadProfileAvatarData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DeleteUploadProfileAvatarData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *DeleteUploadProfileAvatarData) GetAttributes() DeleteUploadProfileAvatarDataAttributes {
	if o == nil {
		var ret DeleteUploadProfileAvatarDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadProfileAvatarData) GetAttributesOk() (*DeleteUploadProfileAvatarDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *DeleteUploadProfileAvatarData) SetAttributes(v DeleteUploadProfileAvatarDataAttributes) {
	o.Attributes = v
}

func (o DeleteUploadProfileAvatarData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadProfileAvatarData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *DeleteUploadProfileAvatarData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteUploadProfileAvatarData := _DeleteUploadProfileAvatarData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteUploadProfileAvatarData)

	if err != nil {
		return err
	}

	*o = DeleteUploadProfileAvatarData(varDeleteUploadProfileAvatarData)

	return err
}

type NullableDeleteUploadProfileAvatarData struct {
	value *DeleteUploadProfileAvatarData
	isSet bool
}

func (v NullableDeleteUploadProfileAvatarData) Get() *DeleteUploadProfileAvatarData {
	return v.value
}

func (v *NullableDeleteUploadProfileAvatarData) Set(val *DeleteUploadProfileAvatarData) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadProfileAvatarData) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadProfileAvatarData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadProfileAvatarData(val *DeleteUploadProfileAvatarData) *NullableDeleteUploadProfileAvatarData {
	return &NullableDeleteUploadProfileAvatarData{value: val, isSet: true}
}

func (v NullableDeleteUploadProfileAvatarData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadProfileAvatarData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


