/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UploadProfileMediaLinksDataRelationshipsProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadProfileMediaLinksDataRelationshipsProfile{}

// UploadProfileMediaLinksDataRelationshipsProfile struct for UploadProfileMediaLinksDataRelationshipsProfile
type UploadProfileMediaLinksDataRelationshipsProfile struct {
	Data UploadProfileMediaLinksDataRelationshipsProfileData `json:"data"`
}

type _UploadProfileMediaLinksDataRelationshipsProfile UploadProfileMediaLinksDataRelationshipsProfile

// NewUploadProfileMediaLinksDataRelationshipsProfile instantiates a new UploadProfileMediaLinksDataRelationshipsProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadProfileMediaLinksDataRelationshipsProfile(data UploadProfileMediaLinksDataRelationshipsProfileData) *UploadProfileMediaLinksDataRelationshipsProfile {
	this := UploadProfileMediaLinksDataRelationshipsProfile{}
	this.Data = data
	return &this
}

// NewUploadProfileMediaLinksDataRelationshipsProfileWithDefaults instantiates a new UploadProfileMediaLinksDataRelationshipsProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadProfileMediaLinksDataRelationshipsProfileWithDefaults() *UploadProfileMediaLinksDataRelationshipsProfile {
	this := UploadProfileMediaLinksDataRelationshipsProfile{}
	return &this
}

// GetData returns the Data field value
func (o *UploadProfileMediaLinksDataRelationshipsProfile) GetData() UploadProfileMediaLinksDataRelationshipsProfileData {
	if o == nil {
		var ret UploadProfileMediaLinksDataRelationshipsProfileData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UploadProfileMediaLinksDataRelationshipsProfile) GetDataOk() (*UploadProfileMediaLinksDataRelationshipsProfileData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UploadProfileMediaLinksDataRelationshipsProfile) SetData(v UploadProfileMediaLinksDataRelationshipsProfileData) {
	o.Data = v
}

func (o UploadProfileMediaLinksDataRelationshipsProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadProfileMediaLinksDataRelationshipsProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UploadProfileMediaLinksDataRelationshipsProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadProfileMediaLinksDataRelationshipsProfile := _UploadProfileMediaLinksDataRelationshipsProfile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadProfileMediaLinksDataRelationshipsProfile)

	if err != nil {
		return err
	}

	*o = UploadProfileMediaLinksDataRelationshipsProfile(varUploadProfileMediaLinksDataRelationshipsProfile)

	return err
}

type NullableUploadProfileMediaLinksDataRelationshipsProfile struct {
	value *UploadProfileMediaLinksDataRelationshipsProfile
	isSet bool
}

func (v NullableUploadProfileMediaLinksDataRelationshipsProfile) Get() *UploadProfileMediaLinksDataRelationshipsProfile {
	return v.value
}

func (v *NullableUploadProfileMediaLinksDataRelationshipsProfile) Set(val *UploadProfileMediaLinksDataRelationshipsProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadProfileMediaLinksDataRelationshipsProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadProfileMediaLinksDataRelationshipsProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadProfileMediaLinksDataRelationshipsProfile(val *UploadProfileMediaLinksDataRelationshipsProfile) *NullableUploadProfileMediaLinksDataRelationshipsProfile {
	return &NullableUploadProfileMediaLinksDataRelationshipsProfile{value: val, isSet: true}
}

func (v NullableUploadProfileMediaLinksDataRelationshipsProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadProfileMediaLinksDataRelationshipsProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


