/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UploadProfileMediaLinksDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadProfileMediaLinksDataRelationships{}

// UploadProfileMediaLinksDataRelationships struct for UploadProfileMediaLinksDataRelationships
type UploadProfileMediaLinksDataRelationships struct {
	Profile *UploadProfileMediaLinksDataRelationshipsProfile `json:"profile,omitempty"`
}

// NewUploadProfileMediaLinksDataRelationships instantiates a new UploadProfileMediaLinksDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadProfileMediaLinksDataRelationships() *UploadProfileMediaLinksDataRelationships {
	this := UploadProfileMediaLinksDataRelationships{}
	return &this
}

// NewUploadProfileMediaLinksDataRelationshipsWithDefaults instantiates a new UploadProfileMediaLinksDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadProfileMediaLinksDataRelationshipsWithDefaults() *UploadProfileMediaLinksDataRelationships {
	this := UploadProfileMediaLinksDataRelationships{}
	return &this
}

// GetProfile returns the Profile field value if set, zero value otherwise.
func (o *UploadProfileMediaLinksDataRelationships) GetProfile() UploadProfileMediaLinksDataRelationshipsProfile {
	if o == nil || IsNil(o.Profile) {
		var ret UploadProfileMediaLinksDataRelationshipsProfile
		return ret
	}
	return *o.Profile
}

// GetProfileOk returns a tuple with the Profile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadProfileMediaLinksDataRelationships) GetProfileOk() (*UploadProfileMediaLinksDataRelationshipsProfile, bool) {
	if o == nil || IsNil(o.Profile) {
		return nil, false
	}
	return o.Profile, true
}

// HasProfile returns a boolean if a field has been set.
func (o *UploadProfileMediaLinksDataRelationships) HasProfile() bool {
	if o != nil && !IsNil(o.Profile) {
		return true
	}

	return false
}

// SetProfile gets a reference to the given UploadProfileMediaLinksDataRelationshipsProfile and assigns it to the Profile field.
func (o *UploadProfileMediaLinksDataRelationships) SetProfile(v UploadProfileMediaLinksDataRelationshipsProfile) {
	o.Profile = &v
}

func (o UploadProfileMediaLinksDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadProfileMediaLinksDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Profile) {
		toSerialize["profile"] = o.Profile
	}
	return toSerialize, nil
}

type NullableUploadProfileMediaLinksDataRelationships struct {
	value *UploadProfileMediaLinksDataRelationships
	isSet bool
}

func (v NullableUploadProfileMediaLinksDataRelationships) Get() *UploadProfileMediaLinksDataRelationships {
	return v.value
}

func (v *NullableUploadProfileMediaLinksDataRelationships) Set(val *UploadProfileMediaLinksDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadProfileMediaLinksDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadProfileMediaLinksDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadProfileMediaLinksDataRelationships(val *UploadProfileMediaLinksDataRelationships) *NullableUploadProfileMediaLinksDataRelationships {
	return &NullableUploadProfileMediaLinksDataRelationships{value: val, isSet: true}
}

func (v NullableUploadProfileMediaLinksDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadProfileMediaLinksDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


