/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the UpdateProfileSessionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProfileSessionData{}

// UpdateProfileSessionData struct for UpdateProfileSessionData
type UpdateProfileSessionData struct {
	// Upload session id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes UpdateProfileSessionDataAttributes `json:"attributes"`
	Relationships UpdateProfileSessionDataRelationships `json:"relationships"`
}

type _UpdateProfileSessionData UpdateProfileSessionData

// NewUpdateProfileSessionData instantiates a new UpdateProfileSessionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProfileSessionData(id uuid.UUID, type_ string, attributes UpdateProfileSessionDataAttributes, relationships UpdateProfileSessionDataRelationships) *UpdateProfileSessionData {
	this := UpdateProfileSessionData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	this.Relationships = relationships
	return &this
}

// NewUpdateProfileSessionDataWithDefaults instantiates a new UpdateProfileSessionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProfileSessionDataWithDefaults() *UpdateProfileSessionData {
	this := UpdateProfileSessionData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateProfileSessionData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateProfileSessionData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateProfileSessionData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateProfileSessionData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateProfileSessionData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateProfileSessionData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateProfileSessionData) GetAttributes() UpdateProfileSessionDataAttributes {
	if o == nil {
		var ret UpdateProfileSessionDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateProfileSessionData) GetAttributesOk() (*UpdateProfileSessionDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateProfileSessionData) SetAttributes(v UpdateProfileSessionDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value
func (o *UpdateProfileSessionData) GetRelationships() UpdateProfileSessionDataRelationships {
	if o == nil {
		var ret UpdateProfileSessionDataRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *UpdateProfileSessionData) GetRelationshipsOk() (*UpdateProfileSessionDataRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *UpdateProfileSessionData) SetRelationships(v UpdateProfileSessionDataRelationships) {
	o.Relationships = v
}

func (o UpdateProfileSessionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProfileSessionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

func (o *UpdateProfileSessionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
		"relationships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateProfileSessionData := _UpdateProfileSessionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateProfileSessionData)

	if err != nil {
		return err
	}

	*o = UpdateProfileSessionData(varUpdateProfileSessionData)

	return err
}

type NullableUpdateProfileSessionData struct {
	value *UpdateProfileSessionData
	isSet bool
}

func (v NullableUpdateProfileSessionData) Get() *UpdateProfileSessionData {
	return v.value
}

func (v *NullableUpdateProfileSessionData) Set(val *UpdateProfileSessionData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProfileSessionData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProfileSessionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProfileSessionData(val *UpdateProfileSessionData) *NullableUpdateProfileSessionData {
	return &NullableUpdateProfileSessionData{value: val, isSet: true}
}

func (v NullableUpdateProfileSessionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProfileSessionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


