/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the UpdateProfileSessionDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProfileSessionDataAttributes{}

// UpdateProfileSessionDataAttributes struct for UpdateProfileSessionDataAttributes
type UpdateProfileSessionDataAttributes struct {
	// JWT upload session token
	UploadToken string `json:"upload_token"`
	// Pre-signed PUT URL for avatar upload
	UploadUrl string `json:"upload_url"`
	// Pre-signed GET URL to read uploaded avatar
	GetUrl string `json:"get_url"`
	// Upload session expiration time
	ExpiresAt time.Time `json:"expires_at"`
}

type _UpdateProfileSessionDataAttributes UpdateProfileSessionDataAttributes

// NewUpdateProfileSessionDataAttributes instantiates a new UpdateProfileSessionDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProfileSessionDataAttributes(uploadToken string, uploadUrl string, getUrl string, expiresAt time.Time) *UpdateProfileSessionDataAttributes {
	this := UpdateProfileSessionDataAttributes{}
	this.UploadToken = uploadToken
	this.UploadUrl = uploadUrl
	this.GetUrl = getUrl
	this.ExpiresAt = expiresAt
	return &this
}

// NewUpdateProfileSessionDataAttributesWithDefaults instantiates a new UpdateProfileSessionDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProfileSessionDataAttributesWithDefaults() *UpdateProfileSessionDataAttributes {
	this := UpdateProfileSessionDataAttributes{}
	return &this
}

// GetUploadToken returns the UploadToken field value
func (o *UpdateProfileSessionDataAttributes) GetUploadToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UploadToken
}

// GetUploadTokenOk returns a tuple with the UploadToken field value
// and a boolean to check if the value has been set.
func (o *UpdateProfileSessionDataAttributes) GetUploadTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadToken, true
}

// SetUploadToken sets field value
func (o *UpdateProfileSessionDataAttributes) SetUploadToken(v string) {
	o.UploadToken = v
}

// GetUploadUrl returns the UploadUrl field value
func (o *UpdateProfileSessionDataAttributes) GetUploadUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UploadUrl
}

// GetUploadUrlOk returns a tuple with the UploadUrl field value
// and a boolean to check if the value has been set.
func (o *UpdateProfileSessionDataAttributes) GetUploadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadUrl, true
}

// SetUploadUrl sets field value
func (o *UpdateProfileSessionDataAttributes) SetUploadUrl(v string) {
	o.UploadUrl = v
}

// GetGetUrl returns the GetUrl field value
func (o *UpdateProfileSessionDataAttributes) GetGetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GetUrl
}

// GetGetUrlOk returns a tuple with the GetUrl field value
// and a boolean to check if the value has been set.
func (o *UpdateProfileSessionDataAttributes) GetGetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GetUrl, true
}

// SetGetUrl sets field value
func (o *UpdateProfileSessionDataAttributes) SetGetUrl(v string) {
	o.GetUrl = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *UpdateProfileSessionDataAttributes) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *UpdateProfileSessionDataAttributes) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *UpdateProfileSessionDataAttributes) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

func (o UpdateProfileSessionDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProfileSessionDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["upload_token"] = o.UploadToken
	toSerialize["upload_url"] = o.UploadUrl
	toSerialize["get_url"] = o.GetUrl
	toSerialize["expires_at"] = o.ExpiresAt
	return toSerialize, nil
}

func (o *UpdateProfileSessionDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"upload_token",
		"upload_url",
		"get_url",
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateProfileSessionDataAttributes := _UpdateProfileSessionDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateProfileSessionDataAttributes)

	if err != nil {
		return err
	}

	*o = UpdateProfileSessionDataAttributes(varUpdateProfileSessionDataAttributes)

	return err
}

type NullableUpdateProfileSessionDataAttributes struct {
	value *UpdateProfileSessionDataAttributes
	isSet bool
}

func (v NullableUpdateProfileSessionDataAttributes) Get() *UpdateProfileSessionDataAttributes {
	return v.value
}

func (v *NullableUpdateProfileSessionDataAttributes) Set(val *UpdateProfileSessionDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProfileSessionDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProfileSessionDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProfileSessionDataAttributes(val *UpdateProfileSessionDataAttributes) *NullableUpdateProfileSessionDataAttributes {
	return &NullableUpdateProfileSessionDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateProfileSessionDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProfileSessionDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


