/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProfile{}

// CreateProfile struct for CreateProfile
type CreateProfile struct {
	Data CreateProfileData `json:"data"`
}

type _CreateProfile CreateProfile

// NewCreateProfile instantiates a new CreateProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProfile(data CreateProfileData) *CreateProfile {
	this := CreateProfile{}
	this.Data = data
	return &this
}

// NewCreateProfileWithDefaults instantiates a new CreateProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProfileWithDefaults() *CreateProfile {
	this := CreateProfile{}
	return &this
}

// GetData returns the Data field value
func (o *CreateProfile) GetData() CreateProfileData {
	if o == nil {
		var ret CreateProfileData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateProfile) GetDataOk() (*CreateProfileData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateProfile) SetData(v CreateProfileData) {
	o.Data = v
}

func (o CreateProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateProfile := _CreateProfile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateProfile)

	if err != nil {
		return err
	}

	*o = CreateProfile(varCreateProfile)

	return err
}

type NullableCreateProfile struct {
	value *CreateProfile
	isSet bool
}

func (v NullableCreateProfile) Get() *CreateProfile {
	return v.value
}

func (v *NullableCreateProfile) Set(val *CreateProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProfile(val *CreateProfile) *NullableCreateProfile {
	return &NullableCreateProfile{value: val, isSet: true}
}

func (v NullableCreateProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


