/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateProfileUsername type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProfileUsername{}

// UpdateProfileUsername struct for UpdateProfileUsername
type UpdateProfileUsername struct {
	Data UpdateProfileUsernameData `json:"data"`
}

type _UpdateProfileUsername UpdateProfileUsername

// NewUpdateProfileUsername instantiates a new UpdateProfileUsername object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProfileUsername(data UpdateProfileUsernameData) *UpdateProfileUsername {
	this := UpdateProfileUsername{}
	this.Data = data
	return &this
}

// NewUpdateProfileUsernameWithDefaults instantiates a new UpdateProfileUsername object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProfileUsernameWithDefaults() *UpdateProfileUsername {
	this := UpdateProfileUsername{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateProfileUsername) GetData() UpdateProfileUsernameData {
	if o == nil {
		var ret UpdateProfileUsernameData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateProfileUsername) GetDataOk() (*UpdateProfileUsernameData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateProfileUsername) SetData(v UpdateProfileUsernameData) {
	o.Data = v
}

func (o UpdateProfileUsername) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProfileUsername) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateProfileUsername) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateProfileUsername := _UpdateProfileUsername{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateProfileUsername)

	if err != nil {
		return err
	}

	*o = UpdateProfileUsername(varUpdateProfileUsername)

	return err
}

type NullableUpdateProfileUsername struct {
	value *UpdateProfileUsername
	isSet bool
}

func (v NullableUpdateProfileUsername) Get() *UpdateProfileUsername {
	return v.value
}

func (v *NullableUpdateProfileUsername) Set(val *UpdateProfileUsername) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProfileUsername) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProfileUsername) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProfileUsername(val *UpdateProfileUsername) *NullableUpdateProfileUsername {
	return &NullableUpdateProfileUsername{value: val, isSet: true}
}

func (v NullableUpdateProfileUsername) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProfileUsername) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


