/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the UpdateProfileSessionDataRelationshipsProfileData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProfileSessionDataRelationshipsProfileData{}

// UpdateProfileSessionDataRelationshipsProfileData struct for UpdateProfileSessionDataRelationshipsProfileData
type UpdateProfileSessionDataRelationshipsProfileData struct {
	// Profile id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
}

type _UpdateProfileSessionDataRelationshipsProfileData UpdateProfileSessionDataRelationshipsProfileData

// NewUpdateProfileSessionDataRelationshipsProfileData instantiates a new UpdateProfileSessionDataRelationshipsProfileData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProfileSessionDataRelationshipsProfileData(id uuid.UUID, type_ string) *UpdateProfileSessionDataRelationshipsProfileData {
	this := UpdateProfileSessionDataRelationshipsProfileData{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewUpdateProfileSessionDataRelationshipsProfileDataWithDefaults instantiates a new UpdateProfileSessionDataRelationshipsProfileData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProfileSessionDataRelationshipsProfileDataWithDefaults() *UpdateProfileSessionDataRelationshipsProfileData {
	this := UpdateProfileSessionDataRelationshipsProfileData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateProfileSessionDataRelationshipsProfileData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateProfileSessionDataRelationshipsProfileData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateProfileSessionDataRelationshipsProfileData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateProfileSessionDataRelationshipsProfileData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateProfileSessionDataRelationshipsProfileData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateProfileSessionDataRelationshipsProfileData) SetType(v string) {
	o.Type = v
}

func (o UpdateProfileSessionDataRelationshipsProfileData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProfileSessionDataRelationshipsProfileData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *UpdateProfileSessionDataRelationshipsProfileData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateProfileSessionDataRelationshipsProfileData := _UpdateProfileSessionDataRelationshipsProfileData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateProfileSessionDataRelationshipsProfileData)

	if err != nil {
		return err
	}

	*o = UpdateProfileSessionDataRelationshipsProfileData(varUpdateProfileSessionDataRelationshipsProfileData)

	return err
}

type NullableUpdateProfileSessionDataRelationshipsProfileData struct {
	value *UpdateProfileSessionDataRelationshipsProfileData
	isSet bool
}

func (v NullableUpdateProfileSessionDataRelationshipsProfileData) Get() *UpdateProfileSessionDataRelationshipsProfileData {
	return v.value
}

func (v *NullableUpdateProfileSessionDataRelationshipsProfileData) Set(val *UpdateProfileSessionDataRelationshipsProfileData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProfileSessionDataRelationshipsProfileData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProfileSessionDataRelationshipsProfileData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProfileSessionDataRelationshipsProfileData(val *UpdateProfileSessionDataRelationshipsProfileData) *NullableUpdateProfileSessionDataRelationshipsProfileData {
	return &NullableUpdateProfileSessionDataRelationshipsProfileData{value: val, isSet: true}
}

func (v NullableUpdateProfileSessionDataRelationshipsProfileData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProfileSessionDataRelationshipsProfileData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


