/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the CreateProfileData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProfileData{}

// CreateProfileData struct for CreateProfileData
type CreateProfileData struct {
	// account id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes CreateProfileDataAttributes `json:"attributes"`
}

type _CreateProfileData CreateProfileData

// NewCreateProfileData instantiates a new CreateProfileData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProfileData(id uuid.UUID, type_ string, attributes CreateProfileDataAttributes) *CreateProfileData {
	this := CreateProfileData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateProfileDataWithDefaults instantiates a new CreateProfileData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProfileDataWithDefaults() *CreateProfileData {
	this := CreateProfileData{}
	return &this
}

// GetId returns the Id field value
func (o *CreateProfileData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateProfileData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateProfileData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *CreateProfileData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateProfileData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateProfileData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateProfileData) GetAttributes() CreateProfileDataAttributes {
	if o == nil {
		var ret CreateProfileDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateProfileData) GetAttributesOk() (*CreateProfileDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateProfileData) SetAttributes(v CreateProfileDataAttributes) {
	o.Attributes = v
}

func (o CreateProfileData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProfileData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateProfileData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateProfileData := _CreateProfileData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateProfileData)

	if err != nil {
		return err
	}

	*o = CreateProfileData(varCreateProfileData)

	return err
}

type NullableCreateProfileData struct {
	value *CreateProfileData
	isSet bool
}

func (v NullableCreateProfileData) Get() *CreateProfileData {
	return v.value
}

func (v *NullableCreateProfileData) Set(val *CreateProfileData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProfileData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProfileData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProfileData(val *CreateProfileData) *NullableCreateProfileData {
	return &NullableCreateProfileData{value: val, isSet: true}
}

func (v NullableCreateProfileData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProfileData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


