/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UploadProfileMediaLinksData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadProfileMediaLinksData{}

// UploadProfileMediaLinksData struct for UploadProfileMediaLinksData
type UploadProfileMediaLinksData struct {
	// key for the media
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes UploadProfileMediaLinksDataAttributes `json:"attributes"`
	Relationships UploadProfileMediaLinksDataRelationships `json:"relationships"`
}

type _UploadProfileMediaLinksData UploadProfileMediaLinksData

// NewUploadProfileMediaLinksData instantiates a new UploadProfileMediaLinksData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadProfileMediaLinksData(id string, type_ string, attributes UploadProfileMediaLinksDataAttributes, relationships UploadProfileMediaLinksDataRelationships) *UploadProfileMediaLinksData {
	this := UploadProfileMediaLinksData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	this.Relationships = relationships
	return &this
}

// NewUploadProfileMediaLinksDataWithDefaults instantiates a new UploadProfileMediaLinksData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadProfileMediaLinksDataWithDefaults() *UploadProfileMediaLinksData {
	this := UploadProfileMediaLinksData{}
	return &this
}

// GetId returns the Id field value
func (o *UploadProfileMediaLinksData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UploadProfileMediaLinksData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UploadProfileMediaLinksData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UploadProfileMediaLinksData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UploadProfileMediaLinksData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UploadProfileMediaLinksData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UploadProfileMediaLinksData) GetAttributes() UploadProfileMediaLinksDataAttributes {
	if o == nil {
		var ret UploadProfileMediaLinksDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UploadProfileMediaLinksData) GetAttributesOk() (*UploadProfileMediaLinksDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UploadProfileMediaLinksData) SetAttributes(v UploadProfileMediaLinksDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value
func (o *UploadProfileMediaLinksData) GetRelationships() UploadProfileMediaLinksDataRelationships {
	if o == nil {
		var ret UploadProfileMediaLinksDataRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *UploadProfileMediaLinksData) GetRelationshipsOk() (*UploadProfileMediaLinksDataRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *UploadProfileMediaLinksData) SetRelationships(v UploadProfileMediaLinksDataRelationships) {
	o.Relationships = v
}

func (o UploadProfileMediaLinksData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadProfileMediaLinksData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

func (o *UploadProfileMediaLinksData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
		"relationships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadProfileMediaLinksData := _UploadProfileMediaLinksData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadProfileMediaLinksData)

	if err != nil {
		return err
	}

	*o = UploadProfileMediaLinksData(varUploadProfileMediaLinksData)

	return err
}

type NullableUploadProfileMediaLinksData struct {
	value *UploadProfileMediaLinksData
	isSet bool
}

func (v NullableUploadProfileMediaLinksData) Get() *UploadProfileMediaLinksData {
	return v.value
}

func (v *NullableUploadProfileMediaLinksData) Set(val *UploadProfileMediaLinksData) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadProfileMediaLinksData) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadProfileMediaLinksData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadProfileMediaLinksData(val *UploadProfileMediaLinksData) *NullableUploadProfileMediaLinksData {
	return &NullableUploadProfileMediaLinksData{value: val, isSet: true}
}

func (v NullableUploadProfileMediaLinksData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadProfileMediaLinksData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


