/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateProfileSessionDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProfileSessionDataRelationships{}

// UpdateProfileSessionDataRelationships struct for UpdateProfileSessionDataRelationships
type UpdateProfileSessionDataRelationships struct {
	Profile *UpdateProfileSessionDataRelationshipsProfile `json:"profile,omitempty"`
}

// NewUpdateProfileSessionDataRelationships instantiates a new UpdateProfileSessionDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProfileSessionDataRelationships() *UpdateProfileSessionDataRelationships {
	this := UpdateProfileSessionDataRelationships{}
	return &this
}

// NewUpdateProfileSessionDataRelationshipsWithDefaults instantiates a new UpdateProfileSessionDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProfileSessionDataRelationshipsWithDefaults() *UpdateProfileSessionDataRelationships {
	this := UpdateProfileSessionDataRelationships{}
	return &this
}

// GetProfile returns the Profile field value if set, zero value otherwise.
func (o *UpdateProfileSessionDataRelationships) GetProfile() UpdateProfileSessionDataRelationshipsProfile {
	if o == nil || IsNil(o.Profile) {
		var ret UpdateProfileSessionDataRelationshipsProfile
		return ret
	}
	return *o.Profile
}

// GetProfileOk returns a tuple with the Profile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProfileSessionDataRelationships) GetProfileOk() (*UpdateProfileSessionDataRelationshipsProfile, bool) {
	if o == nil || IsNil(o.Profile) {
		return nil, false
	}
	return o.Profile, true
}

// HasProfile returns a boolean if a field has been set.
func (o *UpdateProfileSessionDataRelationships) HasProfile() bool {
	if o != nil && !IsNil(o.Profile) {
		return true
	}

	return false
}

// SetProfile gets a reference to the given UpdateProfileSessionDataRelationshipsProfile and assigns it to the Profile field.
func (o *UpdateProfileSessionDataRelationships) SetProfile(v UpdateProfileSessionDataRelationshipsProfile) {
	o.Profile = &v
}

func (o UpdateProfileSessionDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProfileSessionDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Profile) {
		toSerialize["profile"] = o.Profile
	}
	return toSerialize, nil
}

type NullableUpdateProfileSessionDataRelationships struct {
	value *UpdateProfileSessionDataRelationships
	isSet bool
}

func (v NullableUpdateProfileSessionDataRelationships) Get() *UpdateProfileSessionDataRelationships {
	return v.value
}

func (v *NullableUpdateProfileSessionDataRelationships) Set(val *UpdateProfileSessionDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProfileSessionDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProfileSessionDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProfileSessionDataRelationships(val *UpdateProfileSessionDataRelationships) *NullableUpdateProfileSessionDataRelationships {
	return &NullableUpdateProfileSessionDataRelationships{value: val, isSet: true}
}

func (v NullableUpdateProfileSessionDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProfileSessionDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


