/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateProfileSessionDataRelationshipsProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProfileSessionDataRelationshipsProfile{}

// UpdateProfileSessionDataRelationshipsProfile struct for UpdateProfileSessionDataRelationshipsProfile
type UpdateProfileSessionDataRelationshipsProfile struct {
	Data UpdateProfileSessionDataRelationshipsProfileData `json:"data"`
}

type _UpdateProfileSessionDataRelationshipsProfile UpdateProfileSessionDataRelationshipsProfile

// NewUpdateProfileSessionDataRelationshipsProfile instantiates a new UpdateProfileSessionDataRelationshipsProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProfileSessionDataRelationshipsProfile(data UpdateProfileSessionDataRelationshipsProfileData) *UpdateProfileSessionDataRelationshipsProfile {
	this := UpdateProfileSessionDataRelationshipsProfile{}
	this.Data = data
	return &this
}

// NewUpdateProfileSessionDataRelationshipsProfileWithDefaults instantiates a new UpdateProfileSessionDataRelationshipsProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProfileSessionDataRelationshipsProfileWithDefaults() *UpdateProfileSessionDataRelationshipsProfile {
	this := UpdateProfileSessionDataRelationshipsProfile{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateProfileSessionDataRelationshipsProfile) GetData() UpdateProfileSessionDataRelationshipsProfileData {
	if o == nil {
		var ret UpdateProfileSessionDataRelationshipsProfileData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateProfileSessionDataRelationshipsProfile) GetDataOk() (*UpdateProfileSessionDataRelationshipsProfileData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateProfileSessionDataRelationshipsProfile) SetData(v UpdateProfileSessionDataRelationshipsProfileData) {
	o.Data = v
}

func (o UpdateProfileSessionDataRelationshipsProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProfileSessionDataRelationshipsProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateProfileSessionDataRelationshipsProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateProfileSessionDataRelationshipsProfile := _UpdateProfileSessionDataRelationshipsProfile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateProfileSessionDataRelationshipsProfile)

	if err != nil {
		return err
	}

	*o = UpdateProfileSessionDataRelationshipsProfile(varUpdateProfileSessionDataRelationshipsProfile)

	return err
}

type NullableUpdateProfileSessionDataRelationshipsProfile struct {
	value *UpdateProfileSessionDataRelationshipsProfile
	isSet bool
}

func (v NullableUpdateProfileSessionDataRelationshipsProfile) Get() *UpdateProfileSessionDataRelationshipsProfile {
	return v.value
}

func (v *NullableUpdateProfileSessionDataRelationshipsProfile) Set(val *UpdateProfileSessionDataRelationshipsProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProfileSessionDataRelationshipsProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProfileSessionDataRelationshipsProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProfileSessionDataRelationshipsProfile(val *UpdateProfileSessionDataRelationshipsProfile) *NullableUpdateProfileSessionDataRelationshipsProfile {
	return &NullableUpdateProfileSessionDataRelationshipsProfile{value: val, isSet: true}
}

func (v NullableUpdateProfileSessionDataRelationshipsProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProfileSessionDataRelationshipsProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


