/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateProfileSession type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProfileSession{}

// UpdateProfileSession struct for UpdateProfileSession
type UpdateProfileSession struct {
	Data UpdateProfileSessionData `json:"data"`
	Included []ProfileData `json:"included"`
}

type _UpdateProfileSession UpdateProfileSession

// NewUpdateProfileSession instantiates a new UpdateProfileSession object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProfileSession(data UpdateProfileSessionData, included []ProfileData) *UpdateProfileSession {
	this := UpdateProfileSession{}
	this.Data = data
	this.Included = included
	return &this
}

// NewUpdateProfileSessionWithDefaults instantiates a new UpdateProfileSession object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProfileSessionWithDefaults() *UpdateProfileSession {
	this := UpdateProfileSession{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateProfileSession) GetData() UpdateProfileSessionData {
	if o == nil {
		var ret UpdateProfileSessionData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateProfileSession) GetDataOk() (*UpdateProfileSessionData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateProfileSession) SetData(v UpdateProfileSessionData) {
	o.Data = v
}

// GetIncluded returns the Included field value
func (o *UpdateProfileSession) GetIncluded() []ProfileData {
	if o == nil {
		var ret []ProfileData
		return ret
	}

	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value
// and a boolean to check if the value has been set.
func (o *UpdateProfileSession) GetIncludedOk() ([]ProfileData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Included, true
}

// SetIncluded sets field value
func (o *UpdateProfileSession) SetIncluded(v []ProfileData) {
	o.Included = v
}

func (o UpdateProfileSession) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProfileSession) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["included"] = o.Included
	return toSerialize, nil
}

func (o *UpdateProfileSession) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"included",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateProfileSession := _UpdateProfileSession{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateProfileSession)

	if err != nil {
		return err
	}

	*o = UpdateProfileSession(varUpdateProfileSession)

	return err
}

type NullableUpdateProfileSession struct {
	value *UpdateProfileSession
	isSet bool
}

func (v NullableUpdateProfileSession) Get() *UpdateProfileSession {
	return v.value
}

func (v *NullableUpdateProfileSession) Set(val *UpdateProfileSession) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProfileSession) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProfileSession) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProfileSession(val *UpdateProfileSession) *NullableUpdateProfileSession {
	return &NullableUpdateProfileSession{value: val, isSet: true}
}

func (v NullableUpdateProfileSession) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProfileSession) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


