/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UploadProfileMediaLinksDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadProfileMediaLinksDataAttributes{}

// UploadProfileMediaLinksDataAttributes struct for UploadProfileMediaLinksDataAttributes
type UploadProfileMediaLinksDataAttributes struct {
	// Pre-signed URL for uploading the avatar
	UploadUrl string `json:"upload_url"`
	// URL for preloading the avatar after upload
	PreloadUrl string `json:"preload_url"`
}

type _UploadProfileMediaLinksDataAttributes UploadProfileMediaLinksDataAttributes

// NewUploadProfileMediaLinksDataAttributes instantiates a new UploadProfileMediaLinksDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadProfileMediaLinksDataAttributes(uploadUrl string, preloadUrl string) *UploadProfileMediaLinksDataAttributes {
	this := UploadProfileMediaLinksDataAttributes{}
	this.UploadUrl = uploadUrl
	this.PreloadUrl = preloadUrl
	return &this
}

// NewUploadProfileMediaLinksDataAttributesWithDefaults instantiates a new UploadProfileMediaLinksDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadProfileMediaLinksDataAttributesWithDefaults() *UploadProfileMediaLinksDataAttributes {
	this := UploadProfileMediaLinksDataAttributes{}
	return &this
}

// GetUploadUrl returns the UploadUrl field value
func (o *UploadProfileMediaLinksDataAttributes) GetUploadUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UploadUrl
}

// GetUploadUrlOk returns a tuple with the UploadUrl field value
// and a boolean to check if the value has been set.
func (o *UploadProfileMediaLinksDataAttributes) GetUploadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadUrl, true
}

// SetUploadUrl sets field value
func (o *UploadProfileMediaLinksDataAttributes) SetUploadUrl(v string) {
	o.UploadUrl = v
}

// GetPreloadUrl returns the PreloadUrl field value
func (o *UploadProfileMediaLinksDataAttributes) GetPreloadUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PreloadUrl
}

// GetPreloadUrlOk returns a tuple with the PreloadUrl field value
// and a boolean to check if the value has been set.
func (o *UploadProfileMediaLinksDataAttributes) GetPreloadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreloadUrl, true
}

// SetPreloadUrl sets field value
func (o *UploadProfileMediaLinksDataAttributes) SetPreloadUrl(v string) {
	o.PreloadUrl = v
}

func (o UploadProfileMediaLinksDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadProfileMediaLinksDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["upload_url"] = o.UploadUrl
	toSerialize["preload_url"] = o.PreloadUrl
	return toSerialize, nil
}

func (o *UploadProfileMediaLinksDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"upload_url",
		"preload_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadProfileMediaLinksDataAttributes := _UploadProfileMediaLinksDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadProfileMediaLinksDataAttributes)

	if err != nil {
		return err
	}

	*o = UploadProfileMediaLinksDataAttributes(varUploadProfileMediaLinksDataAttributes)

	return err
}

type NullableUploadProfileMediaLinksDataAttributes struct {
	value *UploadProfileMediaLinksDataAttributes
	isSet bool
}

func (v NullableUploadProfileMediaLinksDataAttributes) Get() *UploadProfileMediaLinksDataAttributes {
	return v.value
}

func (v *NullableUploadProfileMediaLinksDataAttributes) Set(val *UploadProfileMediaLinksDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadProfileMediaLinksDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadProfileMediaLinksDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadProfileMediaLinksDataAttributes(val *UploadProfileMediaLinksDataAttributes) *NullableUploadProfileMediaLinksDataAttributes {
	return &NullableUploadProfileMediaLinksDataAttributes{value: val, isSet: true}
}

func (v NullableUploadProfileMediaLinksDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadProfileMediaLinksDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


