/*
NetBill profile service

profile-svc docs

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UploadProfileMediaLinksDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadProfileMediaLinksDataAttributes{}

// UploadProfileMediaLinksDataAttributes struct for UploadProfileMediaLinksDataAttributes
type UploadProfileMediaLinksDataAttributes struct {
	Avatar UploadProfileMediaLinksDataAttributesAvatar `json:"avatar"`
}

type _UploadProfileMediaLinksDataAttributes UploadProfileMediaLinksDataAttributes

// NewUploadProfileMediaLinksDataAttributes instantiates a new UploadProfileMediaLinksDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadProfileMediaLinksDataAttributes(avatar UploadProfileMediaLinksDataAttributesAvatar) *UploadProfileMediaLinksDataAttributes {
	this := UploadProfileMediaLinksDataAttributes{}
	this.Avatar = avatar
	return &this
}

// NewUploadProfileMediaLinksDataAttributesWithDefaults instantiates a new UploadProfileMediaLinksDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadProfileMediaLinksDataAttributesWithDefaults() *UploadProfileMediaLinksDataAttributes {
	this := UploadProfileMediaLinksDataAttributes{}
	return &this
}

// GetAvatar returns the Avatar field value
func (o *UploadProfileMediaLinksDataAttributes) GetAvatar() UploadProfileMediaLinksDataAttributesAvatar {
	if o == nil {
		var ret UploadProfileMediaLinksDataAttributesAvatar
		return ret
	}

	return o.Avatar
}

// GetAvatarOk returns a tuple with the Avatar field value
// and a boolean to check if the value has been set.
func (o *UploadProfileMediaLinksDataAttributes) GetAvatarOk() (*UploadProfileMediaLinksDataAttributesAvatar, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Avatar, true
}

// SetAvatar sets field value
func (o *UploadProfileMediaLinksDataAttributes) SetAvatar(v UploadProfileMediaLinksDataAttributesAvatar) {
	o.Avatar = v
}

func (o UploadProfileMediaLinksDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadProfileMediaLinksDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["avatar"] = o.Avatar
	return toSerialize, nil
}

func (o *UploadProfileMediaLinksDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"avatar",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadProfileMediaLinksDataAttributes := _UploadProfileMediaLinksDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadProfileMediaLinksDataAttributes)

	if err != nil {
		return err
	}

	*o = UploadProfileMediaLinksDataAttributes(varUploadProfileMediaLinksDataAttributes)

	return err
}

type NullableUploadProfileMediaLinksDataAttributes struct {
	value *UploadProfileMediaLinksDataAttributes
	isSet bool
}

func (v NullableUploadProfileMediaLinksDataAttributes) Get() *UploadProfileMediaLinksDataAttributes {
	return v.value
}

func (v *NullableUploadProfileMediaLinksDataAttributes) Set(val *UploadProfileMediaLinksDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadProfileMediaLinksDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadProfileMediaLinksDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadProfileMediaLinksDataAttributes(val *UploadProfileMediaLinksDataAttributes) *NullableUploadProfileMediaLinksDataAttributes {
	return &NullableUploadProfileMediaLinksDataAttributes{value: val, isSet: true}
}

func (v NullableUploadProfileMediaLinksDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadProfileMediaLinksDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


